#+TITLE: Config files for terminal


* folder alacritty

Alacritty - A fast, cross-platform, OpenGL terminal emulator. **Basic alacritty config**

Create a config file in: ~/home/rafatieppo/.config/alacritty/alacritty.yml~

Create a config file in: =/home/rafatieppo/.config/alacritty/alacritty.yml=

* folder tmux

Basic tmux config.

Create a config file in ~/home/rafatieppo/.tmux.conf~

** Terminal palette

#+begin_src 
[[nord]]
    background_color = "#0f1c21"
    cursor_color = "#00485a"
    foreground_color = "#80b6ad"
    palette = "#0f1c21:#046655:#04c975:#b5bd68:#308891:#94a5bc:#8abeb7:#80b6ad:#0f1c21:#046655:#04c975:#b5bd68:#308891:#94a5bc:#8abeb7:#80b6ad"
#+end_src

** Basic commands

+ Ctrl+B D — Detach from the current session.
+ Ctrl+B O — Split the window into two panes horizontally.
+ Ctrl+B E — Split the window into two panes vertically.
+ Ctrl+B Arrow Key (Left, Right, Up, Down) — Move between panes.
+ Ctrl+B X — Close pane.
+ Ctrl+B C — Create a new window.
+ Ctrl+B & — for killing a window
+ Ctrl+B N or P — Move to the next or previous window.
+ Ctrl+B 0 (1,2...) — Move to a specific window by number.
+ Ctrl+B : — Enter the command line to type commands. Tab completion is available.
+ Ctrl+B ? — View all keybindings. Press Q to exit.
+ Ctrl+B W — Open a panel to navigate across windows in multiple sessions.
